IterationMapper
sanbornsen/fabric8-planner pull request #44
Opened 2018-01-09 10:22 UTC by divyanshiGupta

2018-01-09 12:10 UTC, sanbornsen requested changes

2018-01-09 12:10 UTC, sanbornsen commented on src/app/effects/iteration.effects.ts
> +           .do(iterations=> {
How much space is it for indentation?

2018-01-09 12:10 UTC, sanbornsen commented on src/app/effects/iteration.effects.ts
> +                              let iterationMapper: IterationMapper;
What is the use of this variable?
```:TypeName``` is used to define a type not creating an instance of a class. Why not use ```new IterationMapper()``` instead ?

2018-01-09 12:10 UTC, sanbornsen commented on src/app/models/iteration.model.ts
> +  links: string;
As of now we just need one link, that is the self link, So the key should be ```link```.

2018-01-09 12:10 UTC, sanbornsen commented on src/app/models/iteration.model.ts
> +iterationModel: IterationModel;
Please follow proper indentation.

2018-01-09 12:10 UTC, sanbornsen commented on src/app/models/iteration.model.ts
> +  let i;
What is this extra new line for?

2018-01-09 12:10 UTC, sanbornsen commented on src/app/models/iteration.model.ts
> +  for(i=0;i<iterations.length;i=i+1)
Why can't ```i``` be initialized inside the loop?
Maintain spaces inside the for statement (follow the linters)
```for(let i = 0; i < iterations.length; i++)```

2018-01-09 12:10 UTC, sanbornsen commented on src/app/models/iteration.model.ts
> +iterationsUI: IterationUI[];
There is no interface as ```iterationsUI```, it should be singular.

2018-01-09 12:10 UTC, sanbornsen commented on src/app/models/iteration.model.ts
> +
What is this extra blank lines for?

2018-01-09 12:10 UTC, sanbornsen commented on src/app/models/iteration.model.ts
> +IterationModeltoIterationUI(iterations: IterationModel[]): IterationUI[] {
This function name should be same for all the attributes. Let's keep it ```toUIModel```. There should be an interface for mapper classes.

2018-01-09 12:10 UTC, sanbornsen commented on src/app/models/iteration.model.ts
> +IterationUItoIterationModel(iteration: IterationUI): IterationModel {
Similarly this function should also be named, ```toServiceModel```

2018-01-09 12:10 UTC, sanbornsen commented on src/app/models/iteration.model.ts
> +IterationModeltoIterationUI(iterations: IterationModel[]): IterationUI[] {
This function should take one iteration and return one uteration.

2018-01-09 12:29 UTC, divyanshiGupta commented on src/app/models/iteration.model.ts
> +IterationModeltoIterationUI(iterations: IterationModel[]): IterationUI[] {
This is done by _utilMapperUIModel as the above function calls this utility function with single iteration and the utility function returns a single iteration after mapping it to UI model which is then added to array of the UI model.

2018-01-09 13:51 UTC, sanbornsen requested changes

2018-01-09 13:51 UTC, sanbornsen commented on src/app/effects/iteration.effects.ts
> +import { IterationMapper } from '.././models/iteration.model';
Why not just ```./../``` ? What is the use of ```/./``` ?

2018-01-09 13:51 UTC, sanbornsen commented on src/app/effects/iteration.effects.ts
> +                          return new IterationMapper().toUIModel(iterations);
I still see indentation problem here.

2018-01-09 13:51 UTC, sanbornsen commented on src/app/models/iteration.model.ts
> +   for(let i=0; i<iterations.length; i=i+1)
There should be spaces between operators. ```i = 0```, ```i < iterations.length``` etc.

2018-01-09 13:51 UTC, sanbornsen commented on src/app/models/iteration.model.ts
> +
Remove this empty line.

2018-01-09 13:51 UTC, sanbornsen commented on src/app/models/iteration.model.ts
> +   {
Curly braces start from the line above to maintain consistency.

2018-01-09 13:51 UTC, sanbornsen commented on src/app/models/iteration.model.ts
> +
Remove empty line.

2018-01-09 13:51 UTC, sanbornsen commented on src/app/models/iteration.model.ts
> +
Remove empty line

2018-01-09 13:51 UTC, sanbornsen commented on src/app/models/iteration.model.ts
> +
Remove empty lines.

2018-01-09 13:51 UTC, sanbornsen commented on src/app/models/iteration.model.ts
> +   this.iterationModel = this._utilMapperServiceModel(iteration);
Improper indentation.

2018-01-09 13:51 UTC, sanbornsen commented on src/app/models/iteration.model.ts
> +   let iterationModel: IterationModel;
Improper indentation.

2018-01-09 13:51 UTC, sanbornsen commented on src/app/models/iteration.model.ts
> +
Remove empty line

2018-01-09 13:51 UTC, sanbornsen commented
@divyanshiGupta can you write a mapper spec file with some test cases?

2018-01-10 06:14 UTC, divyanshiGupta commented
Ok. I will do that

2018-01-12 10:48 UTC, closed without merging