fix(work-item mapper): Added work-item mapper
sanbornsen/fabric8-planner pull request #55
Opened 2018-02-01 16:14 UTC by divyanshiGupta

2018-02-04 18:57 UTC, sanbornsen requested changes

2018-02-04 18:57 UTC, sanbornsen commented on src/app/models/work-item.ts
> +  sysNumber: string;
make it just ```number```

2018-02-04 18:57 UTC, sanbornsen commented on src/app/models/work-item.ts
> +  wiState: string;
make it just ```state```

2018-02-04 18:57 UTC, sanbornsen commented on src/app/models/work-item.ts
> +  wiState: string;
where is the mapper for this attribute?

2018-02-04 18:57 UTC, sanbornsen commented on src/app/models/work-item.ts
> +  wiDescription: string;
make it just ```description```

2018-02-04 18:57 UTC, sanbornsen commented on src/app/models/work-item.ts
> +  wiDescription: string;
where is the mapper for this attribute?

2018-02-04 18:57 UTC, sanbornsen commented on src/app/models/work-item.ts
> +  lMapper = new LabelMapper();
Why is it ```userMapper``` and ```areaMapper``` for them and just ```lMapper``` for ```label```? Same with the next one. Why is it ```cMapper``` not ```commentMapper```?

2018-02-04 18:57 UTC, sanbornsen commented on src/app/models/work-item.ts
> +  tempToUIModel(arg: WorkItemService, workItemUI: WorkItemUI): WorkItemUI {
Why do we need these extra mapping functions for dependent attributes? Let's recap the flow once - 
* Action dispatch GET_WORKITEMS
* Effect listens for GET_WORKITEMS
* Effect maps it to UI model
* Effect resolves each the work items 
    - Takes the existing UI states of dependent attributes 
    - Pass them on to a function in this class along with one work item and resolve it
* Effect dispatches GET_WORKITEMS_SUCCESS

2018-02-04 18:57 UTC, sanbornsen commented on src/app/models/work-item.ts
> +  tempToServiceModel(arg: WorkItemUI, workItemService: WorkItemService): WorkItemService {
And this is also not needed for the same reason !!

2018-02-05 06:01 UTC, divyanshiGupta commented on src/app/models/work-item.ts
> +  sysNumber: string;
but isnt sysNumber more descriptive about the attribute? as we are getting system.number in this particular attribute.

2018-02-06 12:23 UTC, closed without merging